alias gf='git fetch --all '
alias gl='git log --date=short --pretty=format:"%ad:%Cgreen%an:%Cred%h%d:%Creset%s" '
alias grh='git reset --hard '
alias gs='git status '
alias ga='git add . '
alias gcm='git commit -m '
alias gcf='git commit --fixup=HEAD '
alias gg='git grep -n --break --heading -E '
alias glg='git ls-tree -r --name-only HEAD | grep -E '
alias gri='git rebase -i --autosquash '
